# Site settings
title: Thanos Petsakos
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Thanos Petsakos
user_description: I am a senior data scientist and data analyst from Greece. I am the Founder and CEO of my own company. I am also a Data Science & Data Analysis instructor in several organizations.
user_title: Senior Data Scientist and Data Analyst
email: petsakos1@gmail.com
# twitter_username: lorem_ipsum
instagram_username: thanospetsakos
facebook_username: thanos.petsakos
linkedin_username: thanos-petsakos
github_username:  TPetsakos
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

